### ISSUE TITLE
当我第二次尝试使用时。它把我踢开了。

### ISSUE THREAD

**Issue by rakib7676** [LLM-Red-Team/kimi-free-api#10]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/158442736/59d1863d-44c5-4729-be03-0c9649278965)

当我第二次尝试使用时。它把我踢开了。

**Comment by Vinlic** [comment]
@rakib7676 这看上去只是网站的限制，也许你可以试试搭建API接口访问？

**Comment by rakib7676** [comment]
I am not able to create an API. Thanks for reply me.
