### ISSUE TITLE
在Dify中无法和图片对话

### ISSUE THREAD

**Issue by wwjCMP** [LLM-Red-Team/kimi-free-api#103]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/32979859/901af0cd-7dea-45ce-b7f3-29bdc68cc044)

api是最新版本的。dify里面已经开启了function call

![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/32979859/70fe867f-12fc-43cb-9e03-3bd7b66b4ff6)

**Comment by Vinlic** [comment]
这里只需要Vision支持，不需要function call
kimi的图像理解不是多模态只是OCR，确保你传的图像是包含文本的。
