### ISSUE TITLE
api无法使用

### ISSUE THREAD

**Issue by Coolllh** [LLM-Red-Team/kimi-free-api#108]
我使用axios报{"code":-2001,"message":"请求失败","data":null}这个错误
使用httpclient和postman报Response content: {"code":-2000,"message":"Params body.messages invalid","data":null}
很奇怪

![8efd77add3cb29c41d1033976a96a72](https://github.com/LLM-Red-Team/kimi-free-api/assets/133764286/29ed9c45-6e4c-48f4-b173-d14291759df9)

![8ad3c5838e144ec4c5d1243f6fd9924](https://github.com/LLM-Red-Team/kimi-free-api/assets/133764286/2a353c64-2a6f-4332-baa3-f26bd0e5a6ea)

**Comment by Vinlic** [comment]
1. 请求失败，查看日志确认还有确认refresh token是否可用
2. 代表传送的不是json数据，或者数据缺失，或者content type不为application/json。

**Comment by Coolllh** [comment]
我的token和在https://kimi.moonshot.cn/chat/cpask2g967u5orrdimt0上面获取到的token是一样的

**Comment by Coolllh** [comment]
[2024-05-28 20:42:06.028][error][index<1032,28>] APIException [Error]: 请求失败
    at checkResult (file:///app/dist/index.js:1581:11)
    at createConversation (file:///app/dist/index.js:1219:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/dist/index.js:1266:68
    at async /completions (file:///app/dist/index.js:1779:16) {
  errcode: -2001,
  errmsg: '请求失败',
  data: undefined,
  httpStatusCode: undefined
}
[2024-05-28 20:42:06.028][info][index<983,30>] <- POST /v1/chat/completions 15853ms日志是这样的

**Comment by Coolllh** [comment]
不过我用check查询token是否可用得到的结果都是false

**Comment by Vinlic** [comment]
可以确认是refresh_token不正确不，检查下refresh_token取值，取的位置是否正确

**Comment by Coolllh** [comment]
我是在这里取的token
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/133764286/ca632021-f72d-402d-8c1b-9c4f89dd0942)

**Comment by Coolllh** [comment]
解决了！
