### ISSUE TITLE
我http请求发送成功了，但是返回值好像不太对

### ISSUE THREAD

**Issue by Coolllh** [LLM-Red-Team/kimi-free-api#110]
data: {"id":"cpb9sei34pe5j2n0ee10","model":"kimi","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}],"created":1716952634}

data: [DONE]
这是我的返回值

**Comment by Vinlic** [comment]
这是流式响应，如果想获得同步响应你应该设置stream为false
