### ISSUE TITLE
ERR! chatProcess Error FetchError: request to http://localhost:8000/v1/chat/completions failed, reason: connect ECONNREFUSED ::1:8000

### ISSUE THREAD

**Issue by JosenJin** [LLM-Red-Team/kimi-free-api#111]
ERR! chatProcess Error FetchError: request to http://localhost:8000/v1/chat/completions failed, reason: connect ECONNREFUSED ::1:8000;
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/28665357/a7def6bd-a22f-44d3-85f3-c7252420a37e)

 这是为什么？

**Comment by Vinlic** [comment]
网络不通，检查容器的端口有没有开放
