### ISSUE TITLE
怎么使用python直接在代码里发起http请求呢

### ISSUE THREAD

**Issue by Amengclass** [LLM-Red-Team/kimi-free-api#113]

**Comment by Amengclass** [comment]
import requests
import json

api_key = "替换为apikey了"
url = "https://api.moonshot.cn/v1/chat/completions"
headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json"
}

# 准备请求的数据
data = {
    "model": "kimi",
    "messages": [
        {"role": "system",
         "content": "你是 Kimi，由 Moonshot AI 提供的人工智能助手，你更擅长中文和英文的对话。你会为用户提供安全，有帮助，准确的回答。同时，你会拒绝一切涉及恐怖主义，种族歧视，黄色暴力等问题的回答。Moonshot AI 为专有名词，不可翻译成其他语言。"},
        {"role": "user", "content": "你好，我叫李雷，1+1等于多少？"}
    ],
    "temperature": 0.3,
    "use_search": True,
    "stream": False,
}
data = json.dumps(data)
# 发送POST请求
response = requests.post(url=url, headers=headers, json=data)

# 检查响应状态码
if response.status_code == 200:
    # 解析响应内容
    completion = response.json()
    # 打印消息内容
    print(completion['choices'][0]['message']['content'])
else:
    print(f"请求失败，状态码：{response.text}")

**Comment by Vinlic** [comment]
这里不是官方API，是逆向API，如果要使用需要自己部署kimi-free-api，然后更改地址为free-api地址，api_key使用refresh_token。
