### ISSUE TITLE
docker同时部署qwen & kimi

### ISSUE THREAD

**Issue by scjzhong** [LLM-Red-Team/kimi-free-api#115]
部署qwen 时使用的是8000:8000 部署kimi时使用的是8001:8001，qwen的8000端口http://localhost:8000/v1/chat/completions能正常访问，kimi的8001端口http://localhost:8001/v1/chat/completions无法访问。
部署命令即仓库提供的：docker run -it -d --init --name kimi-free-api -p 8001:8001 -e TZ=Asia/Shanghai vinlic/kimi-free-api:latest。
这个该如何解决？

**Comment by Vinlic** [comment]
docker端口映射参数错误
应该是8001:8000，不是8001:8001

**Comment by scjzhong** [comment]
感谢 感谢
