### ISSUE TITLE
npm run start 后一直输出乱码，help!!!!!!!!!!!!

### ISSUE THREAD

**Issue by CCCpan** [LLM-Red-Team/kimi-free-api#123]
npm run start 后一直输出乱码
![luanma](https://github.com/user-attachments/assets/69ce9841-d3af-43c3-acab-fcffd67efc50)

**Comment by CCCpan** [comment]
用npm node环境跑的，dev start 都不通疯狂输出乱码内容
node v18.7.0 
mac m1
kimi 和tongyi一样的

**Comment by Vinlic** [comment]
这个可能是你的shell环境原因，我们未遇到过
