### ISSUE TITLE
如何实现多轮对话？

### ISSUE THREAD

**Issue by yuyurao** [LLM-Red-Team/kimi-free-api#125]
conversation_id = None 时，报错： {'code': -2000, 'message': 'Params body.conversation_id invalid', 'data': None}

conversation_id = ‘None’ 时，报错： {'code': -2001, 'message': '[请求kimi失败]: 找不到对应的KimiPlus', 'data': None}

**Comment by Vinlic** [comment]
字符串none，没有大写
