### ISSUE TITLE
是否支持对话中的文件上传/超长输入？

### ISSUE THREAD

**Issue by freemedom** [LLM-Red-Team/kimi-free-api#126]
即超长文本输入

**Comment by freemedom** [comment]
理论上直接在content里传过去文本内容（5万字）就行，不过跟网页上的逻辑不一样，网页上是先上传文件。是否有人测试过能否直接传？

**Comment by freemedom** [comment]
官方api价格太贵了，100万tokens/50万汉字，60元

**Comment by Vinlic** [comment]
看文档，文档解析部分

**Comment by Vinlic** [comment]
你的链接是官方的api文档，这个仓库是逆向网页的api，是不一样的，直接看本仓库readme

**Comment by Vinlic** [comment]
需要转换，并且附带base64url的头部，api不提供文件托管，你只能自行编码，服务自动透传到kimi
