### ISSUE TITLE
关于搜索结果

### ISSUE THREAD

**Issue by wwdmy123** [LLM-Red-Team/kimi-free-api#127]
佬，这个搜索结果标注能否优化呢。目前的搜索结果标注是[^5^]，而且这个也不能点进去。可以使用[➊](http://m.jl.offcn.com/html/2024/08/237442.html)这样标注吗

**Comment by Vinlic** [comment]
目前为了兼容微信场景，所以暂时没有使用标记，后续推出聚合free-api会尝试区分处理
