### ISSUE TITLE
上传本地PDF文件，已经转base64格式了，好像没有返回结果

### ISSUE THREAD

**Issue by semibluff888** [LLM-Red-Team/kimi-free-api#129]
def encode_file_to_base64(file_path):
    with open(file_path, "rb") as file:
        encoded_bytes = base64.b64encode(file.read())
        encoded_string = encoded_bytes.decode("utf-8")
    return encoded_string

pdf_file_path=“xxx.pdf”
base64_string = encode_file_to_base64(pdf_file_path)

from openai import OpenAI
 
client = OpenAI(
  api_key="XXX",
  base_url="http://XXX:8000/v1",
)
 
completion = client.chat.completions.create(
  model="moonshot-v1-32k",
  messages=[

    {"role": "user", "content": [
                {
                    "type": "file",
                    "file_url": {
                        "url": base64_string
                    }
                },
                {
                    "type": "text",
                    "text": "文档里说了什么？"
                }
            ]
     
    
    }
      
  ],
  temperature=0.3,
)
 
print(completion.choices[0].message.content)

![image](https://github.com/user-attachments/assets/9219603f-270b-4333-b5cd-444030bbd97a)

**Comment by Vinlic** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/Data_URLs
要求格式是DataURL，请见文档。

**Comment by semibluff888** [comment]
> https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/Data_URLs 要求格式是DataURL，请见文档。

感谢，试了下图片的添加对应类型的数据头可以了，data:image/png;base64,XXX
求教PDF和WORD应该怎么写。。。。试了data:;base64,XXX 或者 data:text/plain;base64,XXX都不行哎

**Comment by semibluff888** [comment]
提示要上传文档：
请上传您想要我阅读的文档，我会分析其中的内容并告诉您文档里说了什么。支持的文档格式包括TXT、PDF、Word文档、PPT幻灯片和Excel电子表格等。

您好!请将文档发送给我,我会仔细阅读文档内容,然后总结并告诉您文档的要点。我会尽量全面地把握文档的核心信息,并用简洁的语言向您汇报。如果您有特别关心的问题,也可以告诉我,我会重点解读相关内容。期待为您服务,让我们一起探索文档的奥秘吧!

**Comment by Vinlic** [comment]
@semibluff888 
文档的MIME类型可以在这里检索扩展名对应的MIME
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
