### ISSUE TITLE
请问一下把这个转出来的接入new-api里面，怎么才能默认开启联网搜索？

### ISSUE THREAD

**Issue by hcppxgit** [LLM-Red-Team/kimi-free-api#13]
是宝塔里面docker部署的

**Comment by Vinlic** [comment]
默认已启用联网搜索，只需要在提示词中提出要求即可，比如：”帮我看一下4090的最新价格。“，kimi那边会进行检索的。
@hcppxgit

**Comment by hcppxgit** [comment]
> 默认已启用以太网搜索，只需要在提示词中提出要求即可，比如：“帮我看看一下4090的最新价格。”，kimi这边会进行搜索的。 @hcppxgit
感谢，我再试试，可能是我的提示词不够明确，先前我问他：”搜索一下现在成都天气”。他回答我：“很抱歉，我无法直接进行网络搜索。不过，您可以通过以下方式自行查看……”
我还问了：“搜索一下今年315曝光了哪些事件”、“今年315曝光了哪些厂商”均没有给我正确结果。
不过后来我尝试问：“搜索一下最近四川山火的新闻”，倒是出现联网搜索结果了。

**Comment by Vinlic** [comment]
@hcppxgit 通常在第一轮的prompt更容易触发联网搜索，往后轮数可能会受影响。

**Comment by Seelery** [comment]
大佬，请问一下在new-api里怎么接入呢，我这样设置的，但是不知道哪里有问题，base url这里是 docker的命令完，Nginx反代了ip+端口
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/28801215/d90151e1-efb8-4faf-b982-c9c3edf084b3)
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/28801215/35f19aea-23d3-449a-8f7c-c48c877e22cc)

**Comment by hcppxgit** [comment]
你都接new了，就别反代了，直接填ip：端口，试试
