### ISSUE TITLE
[FR] 不输出 kimi 的搜索信息

### ISSUE THREAD

**Issue by wwjCMP** [LLM-Red-Team/kimi-free-api#130]
比如下面这些

检索 韩信最经典的一场战役，曾灭项羽20万大军，曾国藩：此计断不可信_百科TA说 - https://baike.baidu.com/tashuo/browse/content?id=fe67b47a8492140206e992db&lemmaId=974908&fromLemmaModule=pcBottom&lemmaTitle=%E6%BD%8D%E6%B0%B4%E4%B9%8B%E6%88%98 ...
检索 韩信一生最经典的四场战役：堪称教科书式的战争典范！_刘邦 - https://www.sohu.com/a/399081000_353840 ...
检索 韩信一生指挥的十大经典战役 - https://www.sohu.com/a/59080289_381837 ...
检索 韩信的最经典战役：井陉之战_赵军 - https://www.sohu.com/a/475778748_120904327 ...
检索 “战神韩信”十大战役之陈仓之战 - https://www.jianshu.com/p/b7e7037539ef ...
检索 韩信兵团_百度百科 - https://baike.baidu.com/item/%E9%9F%A9%E4%BF%A1%E5%85%B5%E5%9B%A2/10185642 ...
检索 韩信（中国西汉初期军事家）_百度百科 - https://baike.baidu.com/item/%E9%9F%A9%E4%BF%A1/5321 ...
检索 韩信 - 搜狗百科 - https://baike.sogou.com/v94292.htm?fromTitle=%E9%9F%A9%E4%BF%A1 ...
检索 韩信打过一些什么有名战役 - 百度知道 - https://zhidao.baidu.com/question/557126162.html ...
检索 韩信一生都有哪些战绩？带你走进兵仙韩信的世界一探究竟！ - https://www.sohu.com/a/385619979_764949 ...
检索 韩信一生最经典的四大决胜计谋，堪称教科书式的战争典范_刘邦_栈道_关中 - https://www.sohu.com/a/795976442_121623574 ...
检索 韩信简介评价_大将军韩信点兵的故事_历史上的韩信怎么死的 - 趣历史网 - https://www.qulishi.com/renwu/hanxin ...
检索 背水一战的主人公-韩信，为什么只有韩信能赢这场战争 - https://www.163.com/dy/article/FBMTV6LV0517DRIV.html ...
检索 黄朴民 张琼：韩信“背水阵”胜因新探 - 爱思想 - https://www.aisixiang.com/data/115446.html ...
检索 韩信：汉朝的奠基者 - 趣历史网 - https://www.qulishi.com/mingxing/a548232.html ...
检索 智勇之将韩信：为何未被派往攻打匈奴？ - 趣历史网 - https://www.qulishi.com/mingxing/a570103.html ...
检索 "韩信"最著名的功绩是什么？_百度知道 - https://zhidao.baidu.com/question/504172925.html ...
检索 从四场战役中揭秘韩信究竟有多厉害，无愧“兵仙”的美誉-趣历史网 - https://www.qulishi.com/article/202008/431704.html ...
检索 韩信一生最经典的四场战役，来看看他有多牛？-趣历史网 - https://www.qulishi.com/article/202104/504427.html ...

**Comment by Vinlic** [comment]
见文档，提供了特定的model名称关闭搜索结果输出
