### ISSUE TITLE
AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by mengjie09** [LLM-Red-Team/kimi-free-api#133]
[2024-08-29 16:30:49.877][success][index<1147,20>] Refresh successful
kimi-free-api-test  | [2024-08-29 16:30:50.191][info][index<1430,22>] 注入提升尾部消息注意力system prompt
kimi-free-api-test  | [2024-08-29 16:30:50.192][info][index<1443,20>] 
kimi-free-api-test  | 对话合并：
kimi-free-api-test  | system:You are a helpful assistant.
kimi-free-api-test  | system:关注用户最新的消息
kimi-free-api-test  | user:Hello!
kimi-free-api-test  | 
kimi-free-api-test  | [2024-08-29 16:30:50.216][error][index<1257,61>] AxiosError: Request failed with status code 400
kimi-free-api-test  |     at settle (file:///app/node_modules/axios/lib/core/settle.js:19:12)
kimi-free-api-test  |     at IncomingMessage.handleStreamEnd (file:///app/node_modules/axios/lib/adapters/http.js:589:11)
kimi-free-api-test  |     at IncomingMessage.emit (node:events:531:35)
kimi-free-api-test  |     at endReadableNT (node:internal/streams/readable:1696:12)
kimi-free-api-test  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
kimi-free-api-test  |     at Axios.request (file:///app/node_modules/axios/lib/core/Axios.js:45:41)
kimi-free-api-test  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
kimi-free-api-test  |     at async fakeRequest (file:///app/dist/index.js:1365:3) {
kimi-free-api-test  |   code: 'ERR_BAD_REQUEST',

**Comment by Vinlic** [comment]
可能需要检查token是否有效
