### ISSUE TITLE
能否一次传送多个文件链接？

### ISSUE THREAD

**Issue by kinghua1971** [LLM-Red-Team/kimi-free-api#134]
首先感谢大佬弄了个如此好用的FREEAPI,在使用过程中我想一次性传送2个或多个文件链接，但不知代码如何写，用教程中的文件链接传送代码一次只能传一个文件链接，请问一次传送多们文件链接的方法是什么？感谢。

**Comment by Vinlic** [comment]
可以传多个，你可以在上下文中放置多条message即可
