### ISSUE TITLE
是不是已经失效了

### ISSUE THREAD

**Issue by huhaku** [LLM-Red-Team/kimi-free-api#138]
无论调用什么接口都是报
[2024-09-24 20:16:22.917][error][index<1020,28>] APIException [Error]: 请求失败
    at checkResult (file:///app/dist/index.js:1579:11)
    at createConversation (file:///app/dist/index.js:1209:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/dist/index.js:1258:68
    at async /completions (file:///app/dist/index.js:1775:16) {
  errcode: -2001,
  errmsg: '请求失败',
  data: undefined,
  httpStatusCode: undefined
}

**Comment by AlanWang2333** [comment]
我也是这个

**Comment by itlwy** [comment]
我也是，刷新了新的token，还是报这个-2001错误码

**Comment by ksweb2** [comment]
我也是，在nextchat里显示：{
  "error": true,
  "message": "empty response from server"
}

**Comment by XYZliang** [comment]
+1，有的 token 又是正常的

**Comment by huhaku** [comment]
不行就多登录几次刷下token吧,有时候可以,有时候又不行,很迷

**Comment by XYZliang** [comment]
去github搜另一个开源项目，不过不是api的形式，是python包，那个能用挺久

**Comment by AlanWang2333** [comment]
> 去github搜另一个开源项目，不过不是api的形式，是python包，那个能用挺久

给个关键词 大佬

**Comment by XYZliang** [comment]
> > 去github搜另一个开源项目，不过不是api的形式，是python包，那个能用挺久
> 
> 给个关键词 大佬

我也忘了，我前几天刚用过。
直接搜kimi，挨个看过去，会找到的

**Comment by Declarcall** [comment]
![请检查refresh token是否可用](https://raw.githubusercontent.com/LLM-Red-Team/kimi-free-api/refs/heads/master/doc/example-0.png "请检查refresh token是否可用")

**Comment by kite8** [comment]
> 去github搜另一个开源项目，不过不是api的形式，是python包，那个能用挺久

大佬, 我翻了好久, 是这个吗: [cheungchazz/cow_plugin_kimichat](https://github.com/cheungchazz/cow_plugin_kimichat)
