### ISSUE TITLE
能不能把其它几家的并进来呀，通过model的不同来决定调用哪一部分

### ISSUE THREAD

**Issue by lizhemin15** [LLM-Red-Team/kimi-free-api#17]
能不能把其它几家的并进来呀，通过model的不同来决定调用哪一部分。目前都想比较着用一下，就得部署好几个服务。

**Comment by Vinlic** [comment]
@lizhemin15 
感谢关注，为了便于独立维护和管理目前是分离的，通过docker部署是很快的，基本1分钟内就能完成部署，如果希望合并api建议通过oneapi等平台中转。
