### ISSUE TITLE
用一星期，账号被嘎了，求教你们正常使用的是怎么配置的？

### ISSUE THREAD

**Issue by walkchen9** [LLM-Red-Team/kimi-free-api#18]
你们的账号还活着吗？

登录提示：无法确定账户状态，请联系管理员

我是搭配cahtgpt next web使用，你们正常使用的是怎么配置的？

**Comment by Vinlic** [comment]
@walkchen9 
最近kimi在封禁非正常渠道访问的用户，可能需要准备备用账号，建议更新到最新版本，最新版本做了一些可能有效的防封处理。
另外使用free-api需要遵循一些规则避免对官方造成运营压力：
1. 尽量不要超过5路并发。
2. 不要将自己账号token共享给多个IP地址使用。
3. 不要讨论敏感话题。

**Comment by onlinedear** [comment]
我觉得可以继续迭代，增加敏感词过滤的第三方api，然后就是任务列队，别出现并发。
