### ISSUE TITLE
求问 token找到了  在哪配置呢 ？

### ISSUE THREAD

**Issue by jenkey2011** [LLM-Red-Team/kimi-free-api#20]
求问 token找到了  在哪配置呢 ？
我用原生部署 拉代码库 然后本地安装启动

**Comment by Vinlic** [comment]
@jenkey2011 服务是零配置的，你的refresh_token只需要作为API_KEY使用即可。
如果使用请求直接调用只需要设置到Authorization: Bearer [refresh_token]

**Comment by jenkey2011** [comment]
> @jenkey2011 服务是零配置的，你的refresh_token只需要作为API_KEY使用即可。 如果使用请求直接调用只需要设置到Authorization: Bearer [refresh_token]

明白了 有好用的UI界面推荐吗……  在线demo里的就行

**Comment by Vinlic** [comment]
@jenkey2011 NextChat、LobeChat、Dify等等，只要支持openai的模型接入，就能支持kimi-free-api。
另外还有[glm-free-api](https://github.com/LLM-Red-Team/glm-free-api)，也可以关注一下。

**Comment by Weihong-Liu** [comment]
请问一下nextchat怎么配置

**Comment by Weihong-Liu** [comment]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/65588374/3ec842f1-f116-4f4b-8b3b-80641081c6cd)

**Comment by Vinlic** [comment]
@Weihong-Liu 
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/20235341/327c97ab-52fa-4f01-abd5-f3758e5189e0)
这样配置

**Comment by Weihong-Liu** [comment]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/65588374/01dc54f4-1031-45c6-b52c-e9e49805e0b4)
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/65588374/adb7b65c-7bae-4250-a5b7-b256f922e8de)
我也是这样配置的，部署在本地8000端口

**Comment by Vinlic** [comment]
@Weihong-Liu 检查refresh_token是否正确，以及去除system设定

**Comment by Weihong-Liu** [comment]
@Vinlic 请问使用的nextchat版本是多少，我使用api请求是可以使用的，可能是nextchat版本有问题
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/65588374/32eb2d77-5b26-4ff0-8478-be5ad5c283cb)

**Comment by Weihong-Liu** [comment]
可以使用了

**Comment by lss182650** [comment]
render部署环境变量key和其他一样吗填写PROXY_SECRET，不写部署不成功

**Comment by lss182650** [comment]
请问部署在render环境变量的api怎么填，不填部署不成功

**Comment by Vinlic** [comment]
@lss182650 服务是零配置的，不需要配置任何东西
refresh token只需要在调用时作为apikey提供

**Comment by lss182650** [comment]
> @lss182650 服务是零配置的，不需要配置任何东西 refresh token只需要在调用时作为apikey提供

可是在render部署失败呀，提示需要提供api值

**Comment by lss182650** [comment]
> > @lss182650 服务是零配置的，不需要配置任何东西 refresh token只需要在调用时作为apikey提供
> 
> 可是在render部署失败呀，提示需要提供api值

提示这个:Your Deploy failed for Web Service kimi-free-api.

**Comment by Vinlic** [comment]
@lss182650 请提供截图，没有遇到过需要填写环境变量的情况

**Comment by lss182650** [comment]
> @lss182650 请提供截图，没有遇到过需要填写环境变量的情况

我在重新部署一遍试试吧
