### ISSUE TITLE
请问不进行长上下文，而是短对话，是否有频率限制？

### ISSUE THREAD

**Issue by kokojacket** [LLM-Red-Team/kimi-free-api#21]
请问不进行长上下文，而是短对话，是否有频率限制？
是否应该准备尽量多的账号用于负载均衡？

**Comment by Vinlic** [comment]
@kokojacket 目前短文本没有限制，频率和并发也暂时没遇到限制，但是最近账号有封禁风险，不建议单账号开大并发，可以准备多几个备用账号。
