### ISSUE TITLE
接入chatgpt on wechat之后似乎无法联网

### ISSUE THREAD

**Issue by kokojacket** [LLM-Red-Team/kimi-free-api#22]
![Clip_2024-03-22_23-02-49](https://github.com/LLM-Red-Team/kimi-free-api/assets/74887370/03c5e400-1470-411e-8904-58f6dc1773b7)

**Comment by Vinlic** [comment]
@kokojacket 检查容器日志查看收到的prompt，是否联网取决于提示词能否唤起kimi的联网检索工具，可以修改提示词唤起

**Comment by kokojacket** [comment]
好的谢谢！

**Comment by phantasy36** [comment]
您好，请问chatgpt-on-wechat中，api直接配置获取到的api，那么模型参数是设置什么？kimi？
以下配置是否对？
moonshot_api_key: 'sk-XXXXXXXXXXXXXXXXXXXX'
MODEL: 'kimi'

**Comment by Vinlic** [comment]
@phantasy36 使用openai的接入方式，模型名称随意，apikey直接使用refresh_token。

**Comment by phantasy36** [comment]
您好，您的chatgpt on wechat是如何配置接入本项目的？
