### ISSUE TITLE
通义千问有打算封装下吗

### ISSUE THREAD

**Issue by lizhemin15** [LLM-Red-Team/kimi-free-api#23]
把逆向也封装成gpt流式回复的这种，那就更好了！谢谢大佬！
https://github.com/leeeduke/revTongYi

**Comment by Vinlic** [comment]
@lizhemin15 已经在计划qwen-free-api。

**Comment by Vinlic** [comment]
@lizhemin15 
https://github.com/LLM-Red-Team/qwen-free-api
已经发布了第一版，后续还会优化。
