### ISSUE TITLE
部署完访问8000端口提示{"code":-1002,"message":"Request is not supported","data":null}

### ISSUE THREAD

**Issue by zhentianxiang** [LLM-Red-Team/kimi-free-api#24]
{"code":-1002,"message":"Request is not supported","data":null}

**Comment by Vinlic** [comment]
@zhentianxiang  free-api不提供webui只提供api服务，请使用本地或在线客户端接入使用，客户端可以选择NextChat，LobeChat或Dify等。

**Comment by Su-Dream** [comment]
我使用NextChat配置kimi-free-api时也提示这个

NextChat配置如下
接口地址：https://example.com/kimiApi
API_KEY：F12中获取的refresh_token

这是kimi的日志文件，前面两条get是我直接访问部署地址，后面的则是通过NextChat请求的

`0|kimi-fre | [2024-04-07 21:47:50.418][info][server.ts<80,24>] <- GET /v1/chat 3ms
0|kimi-fre | [2024-04-07 21:47:52.849][debug][server.ts<75,20>] -> GET / request is not supported - 106.xxx.xxx.7
0|kimi-fre | [2024-04-07 21:47:52.850][info][server.ts<80,24>] <- GET / 1ms
0|kimi-fre | [2024-04-07 21:49:59.037][debug][server.ts<75,20>] -> GET /v1/chat request is not supported - 220.xxx.xxx.73
0|kimi-fre | [2024-04-07 21:49:59.038][info][server.ts<80,24>] <- GET /v1/chat 1ms
0|kimi-fre | [2024-04-07 21:54:42.096][debug][server.ts<75,20>] -> GET /kimiApi/ request is not supported - 127.0.0.1
0|kimi-fre | [2024-04-07 21:54:42.096][info][server.ts<80,24>] <- GET /kimiApi/ 0ms
0|kimi-fre | [2024-04-07 21:58:39.276][debug][server.ts<75,20>] -> POST /kimiApi/v1/chat/completions request is not supported - 127.0.0.1
0|kimi-fre | [2024-04-07 21:58:39.278][info][server.ts<80,24>] <- POST /kimiApi/v1/chat/completions 2ms
0|kimi-fre | [2024-04-07 21:58:39.376][debug][server.ts<75,20>] -> POST /kimiApi/v1/chat/completions request is not supported - 127.0.0.1
0|kimi-fre | [2024-04-07 21:58:39.376][info][server.ts<80,24>] <- POST /kimiApi/v1/chat/completions 0ms
0|kimi-fre | [2024-04-07 22:06:03.451][debug][server.ts<75,20>] -> POST /kimiApi/v1/chat/completions request is not supported - 127.0.0.1
0|kimi-fre | [2024-04-07 22:06:03.452][info][server.ts<80,24>] <- POST /kimiApi/v1/chat/completions 1ms
0|kimi-fre | [2024-04-07 22:08:37.856][debug][server.ts<75,20>] -> POST /kimiApi/v1/chat/completions request is not supported - 127.0.0.1
0|kimi-fre | [2024-04-07 22:08:37.857][info][server.ts<80,24>] <- POST /kimiApi/v1/chat/completions 1ms`

![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/81561787/346d20f9-a8a1-4540-a89f-83385d70ba05)

**Comment by Vinlic** [comment]
@Su-Dream 日志中
/kimiApi/v1/chat/completions request is not supported
已经告知多了/kimiApi这个路径，如果你使用反向代理，请确认你的反代配置是否错误。
