### ISSUE TITLE
Chat调用API超时

### ISSUE THREAD

**Issue by liangshaoze** [LLM-Red-Team/kimi-free-api#28]
通过chatgpt-next-web调用API接口，api.openai.com:443 <--socket error or timeout!超时

**Comment by Vinlic** [comment]
@liangshaoze 应该是模型代理地址没有切换，api.openai.com是OpenAI的地址不是free-api的代理地址。

**Comment by liangshaoze** [comment]
已经解决，需要把BASE_URL指向API地址，不能使用PROXY_URL指向API地址

**Comment by liangshaoze** [comment]
关闭了
