### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by chunzha1** [LLM-Red-Team/kimi-free-api#29]
挂在azure的北美服务器上，连接不上。kimi是否限制了呢（自己本地的mac正常运行）

[2024-03-26 06:59:31.579][info][chat.ts<175,12>] [ { role: 'user', content: 'Say this is a test' } ]
[2024-03-26 06:59:31.581][info][chat.ts<55,10>] Refresh token: 
[2024-03-26 06:59:32.617][error][chat.ts<183,28>] AxiosError [AggregateError]: 
    at Function.AxiosError.from (file:///home/azureuser/mydoc/gpt/kimi-free-api/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///home/azureuser/mydoc/gpt/kimi-free-api/node_modules/axios/lib/adapters/http.js:610:25)
    at RedirectableRequest.emit (node:events:531:35)
    at ClientRequest.eventHandlers.<computed> (/home/azureuser/mydoc/gpt/kimi-free-api/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (file:///home/azureuser/mydoc/gpt/kimi-free-api/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///home/azureuser/mydoc/gpt/kimi-free-api/src/api/controllers/chat.ts:57:20
    at requestToken (file:///home/azureuser/mydoc/gpt/kimi-free-api/src/api/controllers/chat.ts:56:18)
    at acquireToken (file:///home/azureuser/mydoc/gpt/kimi-free-api/src/api/controllers/chat.ts:106:14)
    at fakeRequest (file:///home/azureuser/mydoc/gpt/kimi-free-api/src/api/controllers/chat.ts:301:17) {
  code: 'ETIMEDOUT',
  errors: [
    Error: connect ETIMEDOUT 103.143.17.170:443
        at createConnectionError (node:net:1646:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1705:38)
        at listOnTimeout (node:internal/timers:575:11)
        at processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '103.143.17.170',
      port: 443
    },
    Error: connect ENETUNREACH 240e:940:e009:143:6::2008:443 - Local (:::0)
        at internalConnectMultiple (node:net:1180:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
        at listOnTimeout (node:internal/timers:575:11)
        at processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '240e:940:e009:143:6::2008',
      port: 443
    }
  ],
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 15000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: '*/*',
      'Content-Type': undefined,
      Authorization: 'Bearer 
      Referer: 'https://kimi.moonshot.cn/',
      'Accept-Encoding': 'gzip, deflate, br, zstd',
      'Accept-Language': 'zh-CN,zh;q=0.9',
      Origin: 'https://kimi.moonshot.cn',
      'R-Timezone': 'Asia/Shanghai',
      'Sec-Ch-Ua': '"Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"',
      'Sec-Ch-Ua-Mobile': '?0',
      'Sec-Ch-Ua-Platform': '"Windows"',
      'Sec-Fetch-Dest': 'empty',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Site': 'same-origin',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    },
    method: 'get',
    url: 'https://kimi.moonshot.cn/api/auth/token/refresh',
    data: undefined
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Array],
      timeout: undefined,
      abort: undefined
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/api/auth/token/refresh',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'kimi.moonshot.cn',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/auth/token/refresh'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      _header: 'GET /api/auth/token/refresh HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'Authorization: Bearer 
\r\n' +
        'Referer: https://kimi.moonshot.cn/\r\n' +
        'Accept-Encoding: gzip, deflate, br, zstd\r\n' +
        'Accept-Language: zh-CN,zh;q=0.9\r\n' +
        'Origin: https://kimi.moonshot.cn\r\n' +
        'R-Timezone: Asia/Shanghai\r\n' +
        'Sec-Ch-Ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"\r\n' +
        'Sec-Ch-Ua-Mobile: ?0\r\n' +
        'Sec-Ch-Ua-Platform: "Windows"\r\n' +
        'Sec-Fetch-Dest: empty\r\n' +
        'Sec-Fetch-Mode: cors\r\n' +
        'Sec-Fetch-Site: same-origin\r\n' +
        'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36\r\n' +
        'Host: kimi.moonshot.cn\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/auth/token/refresh',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'kimi.moonshot.cn',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: [TLSSocket],
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://kimi.moonshot.cn/api/auth/token/refresh',
    _timeout: null,
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: AggregateError: 
      at internalConnectMultiple (node:net:1116:18)
      at internalConnectMultiple (node:net:1184:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
      at listOnTimeout (node:internal/timers:575:11)
      at processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error] ]
  }
}[2024-03-26 06:59:32.881][error][chat.ts<219,16>] Stream response error: [2024-03-26 06:59:32.885][warning][chat.ts<220,16>] Try again after 5s...
[2024-03-26 06:59:37.885][info][chat.ts<175,12>] [ { role: 'user', content: 'Say this is a test' } ]
[2024-03-26 06:59:38.145][error][chat.ts<219,16>] Stream response error: [2024-03-26 06:59:38.148][warning][chat.ts<220,16>] Try again after 5s...

**Comment by Vinlic** [comment]
@chunzha1 你可以先通过telnet检查一下服务器和kimi的连接。

**Comment by chunzha1** [comment]
> @chunzha1 你可以先通过telnet检查一下服务器和kimi的连接。

好像是连上了
telnet kimi.moonshot.cn 443
Trying 103.143.17.170...
Connected to 4e219e08b833a913b8545619c61eb96a.volcwaf.com.
Escape character is '^]'.

**Comment by Vinlic** [comment]
@chunzha1 那应该是可以通的，再重试一下看看吧，你可以尝试curl https://kimi.moonshot.cn/api/auth/token/refresh，看能否获得响应。

**Comment by chunzha1** [comment]
> @chunzha1 那应该是可以通的，再重试一下看看吧，你可以尝试curl [https://kimi.moonshot.cn/api/auth/token/refresh，看能否获得响应。](https://kimi.moonshot.cn/api/auth/token/refresh%EF%BC%8C%E7%9C%8B%E8%83%BD%E5%90%A6%E8%8E%B7%E5%BE%97%E5%93%8D%E5%BA%94%E3%80%82)

能够获得响应
 curl  -H "Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6Ik" https://kimi.moonshot.cn/api/auth/token/refresh

{"access_token":"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1c2VyLWNlbnRlciIsImV4cCI6MTcxMTQ0g","refresh_token":"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1c2VyLWNlbnRlciIsImV4cCI6MTc"}

但是调用仍然是一样的错误
curl http://10.0.0.4:8083/v1/chat/completions  -H 'Content-Type: application/json'  -H 'Authorization: Bearer  ' -d '{  "model": "gpt-4",  "messages": [ {"role": "user", "content":"Say this is a test"}]}'
{"code":-1,"message":"Internal error","data":null}

**Comment by Vinlic** [comment]
@chunzha1 我看Authorization: Bearer 后面没有提供refresh_token，加上看看

**Comment by chunzha1** [comment]
> @chunzha1 我看Authorization: Bearer 后面没有提供refresh_token，加上看看

我这里应该是加上了，只是我贴的时候去掉了, eyJhbGciOiJIUzUxMiIsInR5cCI6Ik是refresh_token的前面部分；还是说需要其他额外的？

**Comment by Vinlic** [comment]
@chunzha1 我看你贴的容器日志中Refresh token是空的，说明Authorization头没有正确传值
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/20235341/ac56d21b-64a2-40e4-a789-6be74582fb02)

**Comment by chunzha1** [comment]
> @chunzha1 我看你贴的容器日志中Refresh token是空的，说明Authorization头没有正确传值 ![image](https://private-user-images.githubusercontent.com/20235341/316779172-ac56d21b-64a2-40e4-a789-6be74582fb02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDE2OTAsIm5iZiI6MTcxMTQ0MTM5MCwicGF0aCI6Ii8yMDIzNTM0MS8zMTY3NzkxNzItYWM1NmQyMWItNjRhMi00MGU0LWE3ODktNmJlNzQ1ODJmYjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA4MjMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZTY4NWY2MmQ4YmE0MDZiODljYWMwNjc5ODUzYjI5NGEyYTU4ZjhhZTA5NTJkMWY4MzYyOTk3MjE2YWE3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.exvtTYG7jzJ7PRYnmgH5O7ER6igZw_si4rwthb5W5_Q)

这里是我贴的时候手动去掉了

**Comment by Vinlic** [comment]
@chunzha1 那可能得检查容器的网络是否正常，目前是没遇到过refresh超时的情况

**Comment by chunzha1** [comment]
> @chunzha1 那可能得检查容器的网络是否正常，目前是没遇到过refresh超时的情况

忘了说了，我不是docker部署的，是原生部署的方式；手动改了端口8083然后build。服务器网络应该是正常，目前其他端口的项目还能访问。是否还有其他排查方向？

**Comment by Vinlic** [comment]
@chunzha1 可以重试看看，超时通常是暂时性的，如果在宿主机网络上表现应该一致

**Comment by chunzha1** [comment]
> @chunzha1 可以重试看看，超时通常是暂时性的，如果在宿主机网络上表现应该一致

好吧~感谢回复！我晚点再试试

**Comment by Vinlic** [comment]
@chunzha1 有进一步结果再反馈
