### ISSUE TITLE
不适配chatgpt on wechat

### ISSUE THREAD

**Issue by Payne-Wang** [LLM-Red-Team/kimi-free-api#3]
大佬好，我根据说明配置了这个项目，在将其接入chatgpt on wechat项目时，报错，如下：
[INFO][2024-03-11 08:29:29][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2024-03-11 08:29:29][chat_gpt_session.py:83] - num_tokens_from_messages() is not implemented for model kimi. Returning num tokens assuming gpt-3.5-turbo.
[ERROR][2024-03-11 08:29:33][chat_gpt_bot.py:154] - [CHATGPT] Exception: 'usage'
Traceback (most recent call last):
  File "/data/my_soft/xxxxxxxxxxxxxxxx/bot/chatgpt/chat_gpt_bot.py", line 127, in reply_text
    "total_tokens": response["usage"]["total_tokens"],
KeyError: 'usage'

请问这是什么原因？ps:其他openai的模型，如gpt-4-mobile、gpt-4等是可以用的

**Comment by Vinlic** [comment]
@Payne-Wang 您的项目似乎要求usage字段必须存在，我会在稍后增加这个字段支持来兼容，但是total_tokens值可能并非准确值

**Comment by Payne-Wang** [comment]
> @Payne-Wang 您的项目似乎要求usage字段必须存在，我会在稍后增加这个字段支持来兼容，但是total_tokens值可能并非准确值

没关系的，可以兼容就很好了，谢谢大佬！

**Comment by Vinlic** [comment]
@Payne-Wang 0.0.7版本已经兼容支持

**Comment by Payne-Wang** [comment]
谢谢大佬！
