### ISSUE TITLE
本地部署后无法正常启动

### ISSUE THREAD

**Issue by githup-xfimti** [LLM-Red-Team/kimi-free-api#30]
克隆部署后，访问页面：http://localhost:8000/，返回下面信息，请问如何解决。
{
  "code": -1002,
  "message": "Request is not supported",
  "data": null
}

**Comment by Vinlic** [comment]
@githup-xfimti free-api只提供api服务，不提供webui，你可以通过在线或者本地的客户端接入，LobeChat，NextChat，Dify或其它api中转平台接入。
