### ISSUE TITLE
docker部署后使用非流式访问报错

### ISSUE THREAD

**Issue by xiaozhang959** [LLM-Red-Team/kimi-free-api#34]
佬，用docker部署之后使用非流式访问会报错，报错日志为

`

    [96m[2024-03-30 17:08:29.653][info][index<1203,20>] [ { role: 'system', prompt: 'hi' } ][39m

    [96m[2024-03-30 17:08:29.656][info][index<1119,18>] Refresh token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.省略...[39m

    [32m[2024-03-30 17:08:30.354][success][index<1144,20>] Refresh successful[39m

    [91m[2024-03-30 17:08:30.592][error][index<1230,22>] Stream response error: Cannot read properties of undefined (reading 'replace')[39m

    [93m[2024-03-30 17:08:30.593][warning][index<1231,22>] Try again after 5s...[39m

    [96m[2024-03-30 17:08:35.594][info][index<1203,20>] [ { role: 'system', prompt: 'hi' } ][39m

    [91m[2024-03-30 17:08:36.290][error][index<1230,22>] Stream response error: Cannot read properties of undefined (reading 'replace')[39m

    [93m[2024-03-30 17:08:36.291][warning][index<1231,22>] Try again after 5s...[39m

    [96m[2024-03-30 17:08:41.291][info][index<1203,20>] [ { role: 'system', prompt: 'hi' } ][39m

    [91m[2024-03-30 17:08:42.616][error][index<1230,22>] Stream response error: Cannot read properties of undefined (reading 'replace')[39m

    [93m[2024-03-30 17:08:42.617][warning][index<1231,22>] Try again after 5s...[39m

    [96m[2024-03-30 17:08:47.617][info][index<1203,20>] [ { role: 'system', prompt: 'hi' } ][39m

    [91m[2024-03-30 17:08:48.344][error][index<1032,28>] TypeError: Cannot read properties of undefined (reading 'replace')

        at wrapUrlsToTags (file:///dist/index.js:1311:18)

        at file:///dist/index.js:1303:53

        at Array.reduce (<anonymous>)

        at messagesPrepare (file:///dist/index.js:1295:28)

        at file:///dist/index.js:1209:17

        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

        at async /completions (file:///dist/index.js:1586:16)[39m

    [96m[2024-03-30 17:08:48.347][info][index<985,30>] <- POST /v1/chat/completions 18698ms[39m
`

请问佬，您部署的会出现这个问题嘛？  还是我哪里部署错了

**Comment by Vinlic** [comment]
@xiaozhang959 请提供请求参数确认

**Comment by xiaozhang959** [comment]
`
{
  "model": "kimi-chat",
  "stream": false,
  "messages": [
    {
      "role": "system",
      "prompt": "hi"
    }
  ]
}
`
这是我的参数

**Comment by xiaozhang959** [comment]
嘶...抱歉，我自己参数搞错了。少了个content... 打扰了😅
