### ISSUE TITLE
开启stream，数据传输经常有丢失。

### ISSUE THREAD

**Issue by w2534073922** [LLM-Red-Team/kimi-free-api#36]
使用流式响应时，接收到的结果文本经常有局部内容丢失，即少量间断的残缺。

**Comment by Vinlic** [comment]
@w2534073922 能否提供截图，是否出现乱码字符类似：![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/20235341/569de5b1-639a-418c-a39e-cad566e67663)

**Comment by Vinlic** [comment]
@w2534073922 乱码问题的是已知的，最新0.0.18版本已经处理，内容丢失应该没有，如果有的话麻烦截图确认哈。
