### ISSUE TITLE
不知是否考虑适配OneAPI

### ISSUE THREAD

**Issue by xulei-shl** [LLM-Red-Team/kimi-free-api#4]
项目Docker安装后，可以正常在LobeChat中使用，但不能接入[one-api](https://github.com/songquanpeng/one-api)后调用，不知是否考虑适配

**Comment by Vinlic** [comment]
@xulei-shl 可以提供报错或者问题详情吗，理论上支持gpt兼容格式的都可以接入

**Comment by xulei-shl** [comment]
抱歉，实在不好意思。我将Lobe中的路径配置，直接复制到了OneAPI，末尾多了 `v1`，导致调用错误

**Comment by Vinlic** [comment]
@xulei-shl 好的
