### ISSUE TITLE
能否整合多家接口，弄个 all in one 服务

### ISSUE THREAD

**Issue by tisfeng** [LLM-Red-Team/kimi-free-api#40]
比如我想用 [kimi-free-api](https://github.com/LLM-Red-Team/kimi-free-api) 和 [qwen-free-api](https://github.com/LLM-Red-Team/qwen-free-api) ，目前需要分别启用两个 docker 服务，占用空间较大，如果后面还有类似服务，操作也略微繁琐。

希望能够整合成一个服务，复用代码，也方便在 [one-api](https://github.com/songquanpeng/one-api) 这样的服务中使用。

**Comment by tisfeng** [comment]
也行，先观望看看，期待后面将这些服务整合起来 😌

**Comment by onebytetone** [comment]
> @tisfeng 目前各家的逆向代码有些比较大的差异，并且不确认是否长期稳定，聚集在一起维护不方便，准备等代码稳定后再集合到一个服务上面。

我觉得官方不封，已经不错了。求长期稳定估计不可能。这些官方目前应该是没腾出手来做页面上的安全策略，忙着卷新功能玩法了。  
是这样吧。

**Comment by Vinlic** [comment]
已经在规划中，敬请期待！
