### ISSUE TITLE
auth fail 401

### ISSUE THREAD

**Issue by YP1X** [LLM-Red-Team/kimi-free-api#41]
auth fail 401
Is this still working?

**Comment by Vinlic** [comment]
I confirm that the service is working normally, please check whether your token is wrong.

**Comment by YP1X** [comment]
Error: Not found because of proxy error: Error: Client network socket disconnected before secure TLS connection was established (Status Code: 404)
I believe token is right this time.

**Comment by YP1X** [comment]
I am using botpress cloud platform to build bots.

**Comment by Vinlic** [comment]
@YP1X Can you provide a screenshot of the container log of kimi-free-api? I connected through Dify and found no problem.

**Comment by YP1X** [comment]
404 didn't reoccur. I am not a dev so maybe it's a coding problem.
code:
const kimi_API_KEY = env.kimiFreeKey;

const data = {
    // 模型名称随意填写，如果不希望输出检索过程模型名称请包含silent_search
    "model": "kimi",
    "messages": [
        {
            "role": "user",
            "content": `${workflow.message}`
        }
    ],
    // 是否开启联网搜索，默认false
    "use_search": true,
    // 如果使用SSE流请设置为true，默认false
    "stream": false
}

async function getKimiMessage() {
  try {
    const response = await axios.post('https://api.moonshot.cn/v1/chat/completions', data, {
      headers: {
        Authorization: `Bearer ${kimi_API_KEY}`,
        'Content-Type': 'application/json',
      },
    });

    workflow.response = response.data.choices[0].message.content;
    return workflow.response;
  } catch (error) {
    console.error(error);
    throw error;
  }
}

await getKimiMessage()
  .then((message) => {
    console.log('Kimi message:', message);
  })
  .catch((error) => {
    console.error('Error:', error);
  });
![Screenshot (1150)](https://github.com/LLM-Red-Team/kimi-free-api/assets/38880496/44c13e06-c38d-4fcf-80eb-ba34fc6cf76c)

**Comment by Vinlic** [comment]
@YP1X You may have mistaken the function of kimi-free-api. This is not the official API channel of kimi moonshot ai, but reverses the kimi.ai page function and converts it into an API interface compatible with openai. If you want to use the official moonshot ai interface, please go to https://platform.moonshot.cn/. If you want to use kimi-free-api, please deploy the service yourself and change the proxy address and port, and then change API_KEY to refresh_token.

**Comment by YP1X** [comment]
I may try Dify. THX for your note.
