### ISSUE TITLE
如何使用kimi-free-api分析附件

### ISSUE THREAD

**Issue by laozhuang727** [LLM-Red-Team/kimi-free-api#43]
请问如果要分析一个文件的附件，使用python来调用我们这个kimi-free-api，该如何来做？谢谢

**Comment by Vinlic** [comment]
@laozhuang727 
请阅读文档的文档解读部分：https://github.com/LLM-Red-Team/kimi-free-api?tab=readme-ov-file#%E6%96%87%E6%A1%A3%E8%A7%A3%E8%AF%BB
