### ISSUE TITLE
每一轮会话好像只有第一次提问才能触发联网检索

### ISSUE THREAD

**Issue by SpiritHerb** [LLM-Red-Team/kimi-free-api#44]
联网检索好像只有在每次的会话上第一次提问的时候才会触发，后续问答就不会调用搜索了。我是在Windows系统上原生部署的
我想让它每次会话都能大概率调用网络检索
我没有编程基础，望大佬海涵

**Comment by Vinlic** [comment]
@SpiritHerb 这个是目前的已知问题，可能与对话合并有关，这周或者会尝试优化，但是否检索取决于kimi对于tool调用的规则，不一定能够解决。
对话合并是指，由于平台接口只支持传输一条消息，对于多轮对话将被迫进行对话合并。

**Comment by Vinlic** [comment]
@SpiritHerb 0.0.26已经修复。
