### ISSUE TITLE
小白求教，部署完成后下一步？

### ISSUE THREAD

**Issue by DemonsAH** [LLM-Red-Team/kimi-free-api#46]
想用api批量生成回复，已经完成部署，不需要UI，可以跳过Dify之类的平台自己发请求接回复吗？可以的话想要用[openai提供的python代码](https://platform.openai.com/docs/guides/text-generation/chat-completions-api)类似的实现。根据Dify的示例代码尝试下面的命令，求教正确的url.
```
usr@DESKTOP:~.../kimi-free-api$ curl -X POST "[my_pm2_home]/v1/chat/completions" --header 'Authorization: Bearer eyJ...' --header 'Content-Type: application/json' --data-raw '{}'

curl: (3) URL rejected: No host part in the URL
```

**Comment by Vinlic** [comment]
如果你已经部署在本地并且使用8000端口，可以用以下代码请求。
@DemonsAH 

```cURL
curl --location --request POST 'http://localhost:8000/v1/chat/completions' \
--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1c2VyLWNlbnRlciIsImV4cCI6MTcxOTY4NTcyNiwiaWF0IjoxNzExOTA5NzI2LCJqdGkiOiJjbzRxbW5pbG5sOTZlanRwajRsZyIsInR5cCI6InJlZnJlc2giLCJzdWIiOiJjbzRxbW5pbG5sOTZlanRwajRrZyIsInNwYWNlX2lkIjoiY280cW1uaWxubDk2ZWp0cGo0azAiLCJhYnN0cmFjdF91c2VyX2lkIjoiY280cW1uaWxubDk2ZWp0cGo0amcifQ.c7-jqHIpjRZWc8sZHwCWdkQSxvz9cZs-5o4x2TYiJv1AWgkYBkIoDA28efahv7C1mJFFnQjB0iGTHCKC0LtYEA' \
--header 'Content-Type: application/json' \
--data '{
    "model": "kimi",
    "messages": [
        {
            "role": "user",
            "content": "你是谁？"
        }
    ]
}'
```

响应内容：
```json
{
  "id": "co9bsopldu5r8bme6fp0",
  "model": "kimi",
  "object": "chat.completion",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "我是Kimi，由月之暗面科技有限公司开发的人工智能助手。我在这里为您提供帮助，回答问题，解决问题，并提供信息。无论是日常知识、数据分析还是其他任何问题，只要告诉我，我都会尽力为您提供准确和有用的回答。"
      },
      "finish_reason": "stop"
    }
  ],
  "usage": { "prompt_tokens": 1, "completion_tokens": 1, "total_tokens": 2 },
  "created": 1712504419
}
```

**Comment by DemonsAH** [comment]
感谢大佬回答！可惜仍是不能顺利收到正确的响应内容
使用wsl ubuntu**原生部署**，运行上面的命令得到下面的报错：
```
$ curl --location --request POST 'http://localhost:8000/v1/chat/completions' --header 'Authorization: Bearer eyJhbG...' --header 'Content-Type: application/json' --data '{
    "model": "kimi",
    "messages": [
        {
            "role": "user",
            "content": "你是谁？"
        }
    ]
}'
{"code":-1,"message":"Internal error","data":null}
```
此时pm2 log 有反应同样报错
（如果用本机IP代替localhost报错变为Timeout，pm2 log能收到信息和token）

**Docker部署**
使用windows Docker Desktop部署完成后
使用anaconda直接跑python代码（跟着这个[教程](https://www.bilibili.com/video/BV12m421n7w4/?spm_id_from=333.880.my_history.page.click&vd_source=2c6b6fbb7cac0e84516dad706626a5bc)）
简述操作：python使用opanai的示例代码，修改token和base url
Docker显示如下：
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/83545486/a6430fdb-01ce-4113-9cd9-d33dc7933856)
（使用本机IP代替localhost无区别）

最后尝试Dify和NextChat（跟着这个[教程](https://www.bilibili.com/video/BV1Rm421J7jf/?spm_id_from=333.880.my_history.page.click&vd_source=2c6b6fbb7cac0e84516dad706626a5bc)）
操作与上面无异，即使用OpenAI端口，修改token和base
结果： Dify在设置供应商时Connection error
            NextChat报错 failed to fetch
**问题：** 这些报错是否来自相同的原因？有没有本机为国外IP无法使用服务的可能？

**Comment by Vinlic** [comment]
@DemonsAH base url设置错误，/chat/completions不包含在base url中，另外curl调用有问题需要提供服务的日志截图。
不建议把服务部署在国外服务器，有可能连不上kimi。

**Comment by denghb001** [comment]
作为一个纯小白，遇到了这样的问题
使用windows Docker Desktop部署完成后，
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/59823164/395719ee-231e-48f2-9834-436bf4b5ec81)
运行时出错了
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/59823164/816a0093-3e70-415e-9e0b-5494f0fafd60)

**Comment by Vinlic** [comment]
@denghb001 请查看容器日志并截图方便检查

**Comment by adminlove520** [comment]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/32920883/d5aa0ea9-00dd-4230-82ec-d8613dc9c3ed)
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/32920883/3af5559b-490e-4c88-8d41-b3e1259fb362)
@Vinlic   请问 docker部署好之后，curl成功，但是nextchat内配置之后一直返回
```
{
  "error": true,
  "message": "Failed to fetch"
}
```
和
```
{
  "error": true,
  "message": "empty response from server"
}
```
nextchat配置是这样的
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/32920883/9846818d-2567-49d2-97ff-3114b4075427)

**Comment by Vinlic** [comment]
@adminlove520 检查你在使用nextchat调用时的容器日志

**Comment by adminlove520** [comment]
> @adminlove520 检查你在使用nextchat调用时的容器日志

甚至请求都没到容器日志  vercel部署的nextchat

**Comment by adminlove520** [comment]
但是吧  本地部署的nextchat就可以正常调用  vercel就不行  网络的问题嘛?

**Comment by Vinlic** [comment]
@adminlove520 vercel我测试部署正常，可能得提供更多信息确认。

**Comment by adminlove520** [comment]
> @adminlove520 vercel我测试部署正常，可能得提供更多信息确认。

我感觉应该问题在 我用的vps上  回头搞个国内的主机测试一下  谢谢解惑啦 @Vinlic
