### ISSUE TITLE
NextChat 和 直接curl调接口都返回：Maximum number of redirects exceeded，今天拉的代码本地运行

### ISSUE THREAD

**Issue by mr-dragon** [LLM-Red-Team/kimi-free-api#49]
## 启动方式

```bash
npm i
npm i -g pm2
npm run build
pm2 start dist/index.js --name "kimi-free-api"
pm2 logs kimi-free-api
```

访问：http://localhost:8000/

kimi-free-api已启动！
请通过LobeChat / NextChat / Dify等客户端或OpenAI SDK接入！

## curl测试方式

❯ curl http://localhost:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1c2VyLWNlbnRlciIsImV4cCI6MTcyMDUwOTg3NCwiaWF0IjoxNzEyNzMzODc0LCJqdGkiOiJjb2IzdGNoa3FxNG44aW1wZmduMCIsInR5cCI6InJlZnJlc2giLCJzdWIiOiJjbmFtNmdwa3FxNGhrMGd2b2M0ZyIsInNwYWNlX2lkIjoiY25hbTZncGtxcTRoazBndm9jNDAiLCJhYnN0cmFjdF91c2VyX2lkIjoiY25hbTZncGtxcTRoazBndm9jM2cifQ.LDG9T-v_csI55hbJSmyTZTDoQDn6w5Sr8le6A0wL4f7xNLe8sykpp_b1b4FbneYcRP74nit-XypWJzBNWt1axxx" \
  -d '{
    "model": "kimi",
    "messages": [
        {
            "role": "user",
            "content": "测试"
        }
    ],
    "use_search": false,
    "stream": false}'

{"code":-1000,"message":"Maximum number of redirects exceeded","data":null}

## token获取

![2024-04-10 token](https://github.com/LLM-Red-Team/kimi-free-api/assets/25114117/da8f9d64-20b1-43fc-b074-0b0bea781443)

## 日志

```log
0|kimi-free-api  |     _currentUrl: 'https://kimi.moonshot.cn/api/chat',
0|kimi-free-api  |     _timeout: null,
0|kimi-free-api  |     _isRedirect: true,
0|kimi-free-api  |     [Symbol(shapeMode)]: true,
0|kimi-free-api  |     [Symbol(kCapture)]: false
0|kimi-free-api  |   },
0|kimi-free-api  |   cause: Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded
0|kimi-free-api  |       at RedirectableRequest._processResponse (/GitHub/kimi-free-api/node_modules/follow-redirects/index.js:413:11)
0|kimi-free-api  |       at ClientRequest.RedirectableRequest._onNativeResponse (/GitHub/kimi-free-api/node_modules/follow-redirects/index.js:91:12)
0|kimi-free-api  |       at Object.onceWrapper (node:events:634:26)
0|kimi-free-api  |       at ClientRequest.emit (node:events:519:28)
0|kimi-free-api  |       at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
0|kimi-free-api  |       at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
0|kimi-free-api  |       at Socket.socketOnData (node:_http_client:535:22)
0|kimi-free-api  |       at Socket.emit (node:events:519:28)
0|kimi-free-api  |       at addChunk (node:internal/streams/readable:559:12)
0|kimi-free-api  |       at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
0|kimi-free-api  |     code: 'ERR_FR_TOO_MANY_REDIRE
```

**Comment by Vinlic** [comment]
@mr-dragon 未能复现该问题，看上去是请求被重定向太多次，请检查你的出口网络服务商是否存在异常，建议将服务部署在国内。

**Comment by mr-dragon** [comment]
> @mr-dragon 未能复现该问题，看上去是请求被重定向太多次，请检查你的出口网络服务商是否存在异常，建议将服务部署在国内。

是的 国内，一样的网络环境，在我电脑 m1上，浏览器访问kimi网站正常，用api一样的网络就一直这个，也有可能是 终端被我用了 代理引起，我重新弄下试试
