### ISSUE TITLE
响应速度很慢，请问是官方的问题吗？

### ISSUE THREAD

**Issue by william4s** [LLM-Red-Team/kimi-free-api#5]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/60925835/3609170f-f076-4553-80b5-8c0645590b75)
原生部署的，响应速度很慢，请问是官方的问题吗？

**Comment by Vinlic** [comment]
@william4s 同步请求的话，如果输出token较多，这个耗时是正常的
如果想要获得更及时的输出，建议使用流式输出。
