### ISSUE TITLE
账号达到限制频率

### ISSUE THREAD

**Issue by luminous-123** [LLM-Red-Team/kimi-free-api#58]
作者您好，我在本地使用docker部署后，经过100轮的长对话后，提示
![WechatIMG875](https://github.com/LLM-Red-Team/kimi-free-api/assets/56663326/1fca2140-790a-416a-b97e-38757e766fb4)
我该如何操作

**Comment by Vinlic** [comment]
kimi会经常性调整频率策略，请确保准备足够数量的账号token拼接提供，来突破频率和并发限制。
@luminous-123

**Comment by luminous-123** [comment]
我是自己部署的，应该怎么准备多个token

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月12日 22:23 |
| 收件人 | LLM-Red-Team/kimi-free-api ***@***.***> |
| 抄送人 | luminous ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [LLM-Red-Team/kimi-free-api] 账号达到限制频率 (Issue #58) |

kimi会经常性调整频率策略，请确保准备足够数量的账号token拼接提供，来突破频率和并发限制。
@luminous-123

**Comment by luminous-123** [comment]
这个在Header中加入Authentication，如果写入在openai的create中，应该是添加在哪里，是通过api_key中对token进行多个接入吗

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月12日 22:34 |
| 收件人 | LLM-Red-Team/kimi-free-api ***@***.***> |
| 抄送人 | luminous ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [LLM-Red-Team/kimi-free-api] 账号达到限制频率 (Issue #58) |

@luminous-123 请阅读readme的接入准备部分内容，有提及多token接入

**Comment by Vinlic** [comment]
@luminous-123 都可以，你可以分别添加多个接入或者使用英文逗号拼接它们作为一个KEY接入

**Comment by luminous-123** [comment]
感谢解答！！

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月12日 22:54 |
| 收件人 | LLM-Red-Team/kimi-free-api ***@***.***> |
| 抄送人 | luminous ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [LLM-Red-Team/kimi-free-api] 账号达到限制频率 (Issue #58) |

@luminous-123 都可以，你可以分别添加多个接入或者使用英文逗号拼接它们作为一个KEY接入

**Comment by denghb001** [comment]
> @luminous-123 请阅读readme的接入准备部分内容，有提及多token接入

如果通过python的openai来接入多账号，该怎么操作呢

**Comment by luminous-123** [comment]
> > @luminous-123 请阅读readme的接入准备部分内容，有提及多token接入
> 
> 如果通过python的openai来接入多账号，该怎么操作呢

我是给出多个token候选，然后每一轮随机选择一个token，这个方法一定程度上解决了我的问题

**Comment by denghb001** [comment]
> > > @luminous-123 请阅读readme的接入准备部分内容，有提及多token接入
> > 
> > 
> > 如果通过python的openai来接入多账号，该怎么操作呢
> 
> 我是给出多个token候选，然后每一轮随机选择一个token，这个方法一定程度上解决了我的问题

你是自己建了一个token池，然后随机选吗

**Comment by luminous-123** [comment]
> > > > @luminous-123 请阅读readme的接入准备部分内容，有提及多token接入
> > > 
> > > 
> > > 如果通过python的openai来接入多账号，该怎么操作呢
> > 
> > 
> > 我是给出多个token候选，然后每一轮随机选择一个token，这个方法一定程度上解决了我的问题
> 
> 你是自己建了一个token池，然后随机选吗

对的

**Comment by luminous-123** [comment]
> > > > @luminous-123 请阅读readme的接入准备部分内容，有提及多token接入
> > > 
> > > 
> > > 如果通过python的openai来接入多账号，该怎么操作呢
> > 
> > 
> > 我是给出多个token候选，然后每一轮随机选择一个token，这个方法一定程度上解决了我的问题
> 
> 你是自己建了一个token池，然后随机选吗

对的
