### ISSUE TITLE
测试了下脑筋急转弯都答不上啊，用的是什么模型

### ISSUE THREAD

**Issue by echoyl** [LLM-Red-Team/kimi-free-api#59]
1.米的妈妈是谁
2.花的妈妈是谁
3.米的爸爸是谁

**Comment by Vinlic** [comment]
kimi背后的模型是moonshot 128k
脑筋急转弯不能考量模型的能力，此类问题通常不存在逻辑性，答不对只能说明训练集中此类问题占比很少。
你可以试试glm-free-api的glm4能力，它可以答对。
![Screenshot_2024-04-15-14-33-13-104_mark via](https://github.com/LLM-Red-Team/kimi-free-api/assets/20235341/ca746743-bf07-4c92-b853-9c9c5ce60bff)
