### ISSUE TITLE
你好使用最新版为什么没办法使用

### ISSUE THREAD

**Issue by oyoy2** [LLM-Red-Team/kimi-free-api#6]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/88602736/2ed6f751-dc89-4e21-9150-7f3f660e215a)
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/88602736/acfea300-6a02-4cb4-965f-84d1dceaa1d6)
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/88602736/be4f977b-093c-4db7-94ff-f22712f878a7)

**Comment by Vinlic** [comment]
@oyoy2 你的stream和use_search参数类型不正确，请用bool，不是str。
