### ISSUE TITLE
报错返回：Service Suspended

### ISSUE THREAD

**Issue by tony10124** [LLM-Red-Team/kimi-free-api#60]
首次试用，提取refresh_token，用这方式调用，好使、api返回了模型回答结果。

os.environ["OPENAI_BASE_URL"] = "https://kimi-free-api-nut5.onrender.com/v1"
os.environ["OPENAI_API_KEY"] = refresh_token
然后
response = OpenAI().chat.completions.create( 
model=model,
messages=[
{"role": "user", "content": '你是谁'},
]
)

但是，过几小时后再次试（此前提取refresh_token的win10、edge关机重启过），再次调用，就这报错如下了，已经尝试了刷新页面、重新登录kimi.moonshot.cn发起聊天后再次提取 refresh_token，但都是这报错，求教应如何使用：

    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Service Suspended</title>
</head>
<body>
This service has been suspended.
</body>
</html>

**Comment by tony10124** [comment]
补充报错信息：

    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Service Suspended</title>
</head>
<body>
This service has been suspended.
</body>
</html>

**Comment by tony10124** [comment]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/130659497/814214d2-bf6c-4dcb-8098-470d8ebef492)
重发报错信息截屏。此前发文字版、会被平台过滤掉部分文字

**Comment by Vinlic** [comment]
@tony10124 请自行部署，render上部署的测试地址昨晚已经过期，我已经下线该地址，现在不可用。

**Comment by tony10124** [comment]
哦，明白了，谢谢
