### ISSUE TITLE
是否支持输入system prompt?

### ISSUE THREAD

**Issue by DeoLeung** [LLM-Red-Team/kimi-free-api#61]
我看服务日志有打印system内容, 不知道这部分是否支持用户自定义?

**Comment by Vinlic** [comment]
@DeoLeung 支持，设定方式与openai一致，但官方已经设定过一重kimi身份，不建议重复设定容易引起幻觉。

**Comment by Vinlic** [comment]
@DeoLeung 支持，设定方式与openai一致，但官方已经设定过一重kimi身份，不建议重复设定容易引起幻觉。
