### ISSUE TITLE
[请求glm失败]: bad request

### ISSUE THREAD

**Issue by lling1234** [LLM-Red-Team/kimi-free-api#62]
curl --location 'http://localhost:8000/v1/chat/completions' \
--header 'Authorization: Bearer eyJhbGciOiJIUxxxxxx' \
--header 'Content-Type: application/json' \
--data '{
    "model": "kimi",
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "file",
                    "file_url": {
                        "url": "https://mj101-1317487292.cos.ap-shanghai.myqcloud.com/ai/test.pdf"
                    }
                },
                {
                    "type": "text",
                    "text": "文档里说了什么？"
                }
            ]
        }
    ],
    "use_search": false
}'

响应结果：
{
    "code": -2001,
    "message": "[请求glm失败]: bad request",
    "data": null
}

**Comment by Vinlic** [comment]
@lling1234 你请求的似乎是glm-free-api，而不是kimi-free-api。
