### ISSUE TITLE
使用dify发布服务如何配置

### ISSUE THREAD

**Issue by Cone1989** [LLM-Red-Team/kimi-free-api#65]
您好，目前我已经实现如下步骤：
1. 本地部署并调试，可以调用kimi并进行对话；
2. 修改为公网ip部署；

现在想照着该项目一样在dify部署一下，在dify中使用哪个工具调用自己的服务？

**Comment by Vinlic** [comment]
![189a77532de0bf173142633bdd68a8e](https://github.com/LLM-Red-Team/kimi-free-api/assets/20235341/5cbe3d24-a0fe-408a-ae3b-46cfd12301a7)
![ff32a127f9aa4366f4ff581fd8a54b0](https://github.com/LLM-Red-Team/kimi-free-api/assets/20235341/5b3af8bd-52f5-4563-97ec-06cab79f9bc2)

**Comment by forhonourlx** [comment]
@Vinlic 楼主，继续请教下dify中如何配置kimi-search等联网模式？
怎么配置"use_search": true, "model": true, ?
感谢感谢！

![Image](https://github.com/user-attachments/assets/b6b28d5a-a33c-4b05-b865-9a4d22e6fe9b)

![Image](https://github.com/user-attachments/assets/6d17b699-df54-48fb-80f1-93282fcdf23c)
