### ISSUE TITLE
今天被封号了

### ISSUE THREAD

**Issue by andrewcapture** [LLM-Red-Team/kimi-free-api#67]
感谢作者，今天被封号了

**Comment by haso2007** [comment]
哈哈哈，我也是，还以为出了什么问题。不能开心的玩耍了

**Comment by Vinlic** [comment]
@andrewcapture @haso2007 
更新了0.0.28版本，如果有多余账号可以测试一下。

**Comment by Phamay** [comment]
哎也被封了

**Comment by freemandealer** [comment]
封号的原理是啥？这里不是模拟了请求了吗？

**Comment by myvica** [comment]
> 封号的原理是啥？这里不是模拟了请求了吗？

大部分的请求IP一查就清楚了吧
