### ISSUE TITLE
请问在DOCKER里应如何设置Authorization: Bearer TOKEN1,TOKEN2,TOKEN3

### ISSUE THREAD

**Issue by cq134cq** [LLM-Red-Team/kimi-free-api#70]
请问在DOCKER里应如何设置Authorization: Bearer TOKEN1,TOKEN2,TOKEN3

**Comment by Vinlic** [comment]
服务是零配置的，token请在调用时作为APIKEY提供。

**Comment by Vinlic** [comment]
@cq134cq one api可以添加为多个渠道，每个渠道用不同token作为key

**Comment by WyInnovate** [comment]
> @cq134cq one api可以添加为多个渠道，每个渠道用不同token作为key
@Vinlic 
NextChat中，接口地址是http://xxxx:8126/v1，这样写吗？然后KEY是直接写token吗？

**Comment by Vinlic** [comment]
@WyInnovate 如果你使用oneapi，请填写oneapi的key，如果没有使用，就填refresh token
nextchat的代理地址不用带/v1
