### ISSUE TITLE
如何上传本地文件，而非URL

### ISSUE THREAD

**Issue by auroralzone** [LLM-Red-Team/kimi-free-api#71]
如何上传本地文件，而非URL？

![code1](https://github.com/LLM-Red-Team/kimi-free-api/assets/42070770/5a63ab5b-b34a-49de-be4e-33008fbad497)

**Comment by Vinlic** [comment]
@auroralzone 请将文件编码为base64作为url即可，记得加上数据头，比如jpeg的数据头是data:image/jpeg;base64,XXXX

**Comment by auroralzone** [comment]
成功运行。
如何设置才能根据文档连续上下文，回答第二、三...个问题呢？

**Comment by Vinlic** [comment]
全量传送多轮上下文，在当前消息下面增加新的消息对象。

**Comment by auroralzone** [comment]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/42070770/d37991c5-41a3-4b6a-9210-fc8e238184d6)
好像不行

**Comment by Vinlic** [comment]
@auroralzone 不了解你想实现什么功能，请提供全量上下文检查

**Comment by auroralzone** [comment]
我用代码上传文件，第一问成功。
第二个问题的回答，并没有关联到第一个问题。

![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/42070770/39a71483-a705-49c5-b071-5d0309dee069)

![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/42070770/75f82660-c532-40c5-a9f7-959f35d086ff)

![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/42070770/bc38a588-cbb2-4dd5-b37d-911620b558f7)

**Comment by Vinlic** [comment]
为了节省上下文，我们只会上传最后一轮的文件，如果想要反复对同个文件询问，请在每一轮都附带它

**Comment by auroralzone** [comment]
用参考的代码实现不？

**Comment by auroralzone** [comment]
大佬，有没有别的版本呢？
我需要一个文件，问多轮问题的

**Comment by Vinlic** [comment]
多轮上下文全量传送的时候，最后一条就用消息和文档一起传送即可

**Comment by Vinlic** [comment]
```json
{
    // 模型名称随意填写，如果不希望输出检索过程模型名称请包含silent_search
    "model": "kimi",
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "file",
                    "file_url": {
                        "url": "https://mj101-1317487292.cos.ap-shanghai.myqcloud.com/ai/test.pdf"
                    }
                },
                {
                    "type": "text",
                    "text": "文档里说了什么？"
                }
            ]
        },
        {
            "role": "assistant",
            "content": "这个文档是..."
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "file",
                    "file_url": {
                        "url": "https://mj101-1317487292.cos.ap-shanghai.myqcloud.com/ai/test.pdf"
                    }
                },
                {
                    "type": "text",
                    "text": "详细说说？"
                }
            ]
        }
    ],
    // 建议关闭联网搜索，防止干扰解读结果
    "use_search": false
}
```
