### ISSUE TITLE
errmsg: 'Params body.messages invalid',

### ISSUE THREAD

**Issue by Bald0Wang** [LLM-Red-Team/kimi-free-api#75]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/38057320/d119b6f8-2174-4e6b-866c-87f6a712bfad)
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/38057320/589f4e73-d141-48a7-9f99-33c1366785f7)
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/38057320/7446c728-a3c3-45d4-a7a1-01f3d565aea3)

**Comment by Bald0Wang** [comment]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/38057320/30a78744-cd4a-4b06-86e9-9912ef841105)
是不是这个结构改了？！

**Comment by Vinlic** [comment]
@Bald0Wang 请不要取消你请求工具中的默认header，这导致content type未进行传送，框架无法识别你发送的数据是json

**Comment by Bald0Wang** [comment]
get  
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/38057320/902b1571-bfaf-419e-aa96-59c50b7088c4)

目前报了502错误  同样方式可以使用qwen

**Comment by Bald0Wang** [comment]
搞定！

**Comment by Bald0Wang** [comment]
谢谢大佬  感谢回复！辛苦了！
