### ISSUE TITLE
api /token/check  请求不支持

### ISSUE THREAD

**Issue by xiaokaRepo** [LLM-Red-Team/kimi-free-api#76]
POST /token/check

body:
{
   "token":"xxxx"
}

{
  "code": -1002,
  "message": "Request is not supported",
  "data": null
}

**Comment by Vinlic** [comment]
请提供截图，路径不要加/v1

**Comment by xiaokaRepo** [comment]
![CleanShot 2024-04-21 at 15 12 05](https://github.com/LLM-Red-Team/kimi-free-api/assets/141160532/7322fa74-a8c7-4cdd-9ae4-39f7f93a34a5)

**Comment by Vinlic** [comment]
@xiaokaRepo 查看容器日志和确认服务版本
