### ISSUE TITLE
之前好好的，突然失败

### ISSUE THREAD

**Issue by auroralzone** [LLM-Red-Team/kimi-free-api#85]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/42070770/d08148f3-76b0-4f7c-bb75-e7fdc3c6fbe8)

![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/42070770/4f4031e0-c3d9-485d-9303-2c6ca0f921d4)

改了`refresh_token`依然不行

**Comment by Vinlic** [comment]
检查你的free-api容器日志

**Comment by auroralzone** [comment]
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/42070770/c1f38b71-4696-4265-93d5-c7ef57265a1f)

![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/42070770/1d5c8318-b2ba-4354-b617-a539173c2676)

**Comment by Vinlic** [comment]
无法连接到kimi平台接口，请检查你的网络，或者更换网络环境。
