### ISSUE TITLE
你好请问能否在chatgpt-on-wechat中使用？

### ISSUE THREAD

**Issue by phantasy36** [LLM-Red-Team/kimi-free-api#88]
chatgpt-on-wechat中，需要配置api和模型。api就是项目获取的api这个应该是没有问题的，但是模型应该如何填写？

**Comment by Vinlic** [comment]
模型名称没有限制，可以乱填

**Comment by phantasy36** [comment]
> 模型名称没有限制，可以乱填

感谢。

**Comment by phantasy36** [comment]
> 模型名称没有限制，可以乱填

按照我上面的配置，代理设置为http://192.168.8.60:8000，机器人回复
[ERROR]
我连接不到你的网络
