### ISSUE TITLE
chatgpt-on-wechat不兼容返回的tokens为0，导致回复出问题

### ISSUE THREAD

**Issue by ityyds** [LLM-Red-Team/kimi-free-api#9]
api返回数据
![1](https://github.com/LLM-Red-Team/kimi-free-api/assets/75478240/764b605b-b9e5-4df8-9cdb-a8a573cb9166)
出现问题
![屏幕截图 2024-03-17 020706](https://github.com/LLM-Red-Team/kimi-free-api/assets/75478240/4486e234-09a4-4eef-94eb-bb9bd9210236)
主要是我修改了chatgpt-on-wechat的代码，但是不会打包成docker，望求作者能修复一下，或者返回一个限位的随机值可不可行

**Comment by Vinlic** [comment]
@ityyds 好的，处理后会同步上来

**Comment by Vinlic** [comment]
@ityyds 请拉取最新镜像

**Comment by ityyds** [comment]
> @ityyds 请拉取最新镜像

大佬太感谢了，没想到这么晚还在，我一头扎进去研究，现在才看到回复，我马上测试一下

**Comment by ityyds** [comment]
> @ityyds请拉取最新镜像

测试通过，已经正常运行，太感谢辣
![image](https://github.com/LLM-Red-Team/kimi-free-api/assets/75478240/415e8c03-16da-41e0-a327-6c5646d336b3)
