### ISSUE TITLE
关于使用时不明白的问题

### ISSUE THREAD

**Issue by lzk821** [LLM-Red-Team/kimi-free-api#92]
我按照您的教程部署了docker-compose项目，打开项目显示启动成功。但是我还是不明白这个的使用方法，比如说获取的token怎么使用，是搭建时作为环境变量使用还是说是其他方法。您写的文档很详细，但是作为小白的我来说还是看不太懂。

**Comment by Vinlic** [comment]
此服务部署后不需要进行任何配置，你只需要通过文档中推荐使用的客户端接入或者代码接入即可，refresh_token作为API_KEY使用即可。

**Comment by lzk821** [comment]
> 此服务部署后不需要进行任何配置，你只需要通过文档中推荐使用的客户端接入或者代码接入即可，refresh_token作为API_KEY使用即可。

我已经将refresh_token作为api-key使用了，试了lobeHub和nextChat,接口地址使用的公网部署地址+//v1/chat/completions，api_key填的是refresh_token的值，但是使用时会报错
{
  "error": true,
  "message": "empty response from server"
}
，佬这个怎么解决？我使用的智谱这个项目

**Comment by Vinlic** [comment]
应该请求地址不正确或者和服务的网络不通，请检查请求地址
lobechat的地址请根据占位符要求填写，是没有/chat/completions这部分的。

**Comment by lzk821** [comment]
> 应该请求地址不正确或者和服务的网络不通，请检查请求地址 lobechat的地址请根据占位符要求填写，是没有/chat/completions这部分的。

佬，是写在openai这个模型这里吗，模型选择选3.5还是？我地址和api应该是没有问题的，搭建的服务也可以正常手动访问
