### ISSUE TITLE
什么情况下会封号？

### ISSUE THREAD

**Issue by ChitaGideon** [LLM-Red-Team/kimi-free-api#95]
看了下  issue #68 #67  关于封号不是罕见的问题，我想了解下，在什么情况下容易封号呢，给后人也多个提示。

比如我自己的号，可能一共就用服务发了5句话，第二天就没法用了。

估计不是频率和并发导致的封号，可能是因为服务部署在国外、或者ip不是常用地址导致的封号？

你们封号是什么情况呢？

**Comment by Vinlic** [comment]
通常kimi的封号是每隔一段时间就会进行，目前新一轮的还未开始，不建议将服务部署在国外。

**Comment by danepoirier0** [comment]
是不是Axios运行在Nodejs上，被识别出来了？其它语言的一些做这种逆向的一般都是使用修改过Tls指纹的http请求库

**Comment by Vinlic** [comment]
目前厂商通过行为识别逆向是很简单的，还不需要强化对TLS指纹识别，而且如果强化到TLS指纹识别那组织的目的也已经达到了

**Comment by mo-han** [comment]
如果直接模拟操作浏览器呢
